version: '2'

volumes:
  dbdata_mysql_maria:

services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.5.2
    container_name: americor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: americor-test
    volumes:
      - "dbdata_mysql_maria:/var/lib/mysql"
    ports:
      # Для доступа с хостовой машины в phpmyadmin
      # docker run -d --name phpmyadmin -e PMA_HOST=$(docker exec americor-mysql ip route show | head -n 1 | cut -d ' ' -f 3) -e PMA_PORT=3503 -p 8082:80 phpmyadmin
      # http://localhost:8082/
      - 3503:3306